### PR TITLE
Upgrade packages to fix problem with NetStandard packages

### PR DESCRIPTION
**Pull request by llehn**
This is a fix for this issue: https://github.com/themotleyfool/Klondike/issues/157
The error goes away with the upgraded nuget.core. 
I upgraded more packages where only the major version did not change.
Additionally I replaced RX 2.2.5 with new RX 3.0 packages (different package names). Only for .NET > 4.0

Additionally I fixed a problem with implicit datetime to datetimeoffset conversion:
`var d = (DateTimeOffset)default(DateTime)`
throws an exception in time zones with positive UTC offset.

All tests still pass

### CODE REVIEW

**Comment by llehn** [comment]
The build breaks because of out-of-date nuget.exe

**Comment by chriseldredge** [comment]
I just pushed a fix to master that gets the latest version of nuget.exe. This should fix the build error if you rebase or merge master into your pull request.

**Comment by llehn** [comment]
rebase done

**Comment by chriseldredge** [comment]
Would have been nice to have e45bb46b787bf0e20059d9364a2af329f0ce1950 in a separate PR/issue since it seems unrelated. Do you have any background information on why this change is necessary? Think it's possible to put a unit test around it?

**Comment by llehn** [comment]
yes I should have done that in a separate pr. the change was necessary because without it the code threw exceptions, breaking unit tests. some background info:

the issue is the same as in this SO question http://stackoverflow.com/questions/6924198/converting-datetime-minvalue-to-datetimeoffset

when the FirstOrDefault tried to create a default datetime when the sequence is empty, it does so with the defaut(Datetime), which is datetime.minvalue in local time. when implicitely converting that to Datetimeoffset, the value used for convertion is UTC time, which is less than Minvalue (it is minvalue-x) if the timezone is utc+x. and this leads to an exception as documented here: https://msdn.microsoft.com/en-us/library/system.datetimeoffset.op_implicit(v=vs.110).aspx

by changing the default(datetime) to be in UTC, we prevent it from being lower than datetimeoffset.minvalue

**Pull request merged**
